apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: kamaji
        git:
          depth: 1
          url: https://github.com/clastix/kamaji
          ref: "edge-25.12.3"
        includePaths:
          - charts/**/*
  - path: helm/kamaji
    contents:
    - path: .
      directory:
        path: vendor/kamaji
      excludePaths:
        - charts/kamaji/Makefile
        - charts/kamaji/README.md*
        - charts/kamaji/values.sample.yaml
        - charts/kamaji/crds/**
        - charts/kamaji-crds/Makefile
        - charts/kamaji-crds/README.md*