apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: vendor
    contents:
      - path: kamaji
        git:
          depth: 1
          url: https://github.com/clastix/kamaji
          ref: "edge-25.12.3"
        includePaths:
          - charts/**/*
  - path: helm/kamaji
    contents:
    - path: .
      directory:
        path: vendor/kamaji/charts/kamaji
      excludePaths:
        - Makefile
        - README.md*
        - values.sample.yaml
        - crds/**
        - .helmignore
  # Sync crds chart ouutside of the main kamaji chart as vendir does
  # not allow management of nested paths, but we can still retain the
  # vendir logic to exclude files we don't want. We manually move the
  # crds chart into the right place in sync.sh later.
  - path: helm/kamaji-crds
    contents:
    - path: .
      directory:
        path: vendor/kamaji/charts/kamaji-crds
      excludePaths:
        - Makefile
        - README.md*
