apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: kamaji
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: kamaji
  egress:
    - toEntities:
        - kube-apiserver
    - toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: kamaji-etcd
          matchExpressions:
            - key: io.kubernetes.pod.namespace
              operator: Exists
      toPorts:
        - ports:
            - port: "2379"
  ingress:
  - fromEntities:
    - cluster
    - kube-apiserver
