apiVersion: v2
# upstream chart version
appVersion: UPSTREAM_SYNC_VERSION
# giantswarm chart version
version: REPLACE_CHARTVERSION
name: kamaji
type: application
description: Kamaji is the Hosted Control Plane Manager for Kubernetes.
home: https://github.com/giantswarm/kamaji-app
icon: https://s.giantswarm.io/app-icons/kamaji/2/light.svg
kubeVersion: ">=1.21.0-0"
maintainers:
  - name: Team Rocket
    email: team-rocket@giantswarm.io
annotations:
  io.giantswarm.application.team: "rocket"
  io.giantswarm.application.audience: "giantswarm"
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.upstream-chart-url: "https://github.com/clastix/kamaji"
  io.giantswarm.application.upstream-chart-version: "UPSTREAM_SYNC_VERSION"
dependencies:
- name: kamaji-crds
  version: REPLACE_CRDVERSION
sources:
- https://github.com/clastix/kamaji
